version: 2.1
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@2.1.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.04 
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      #installing dependencies
      - run:
          name: Install Frontend
          command: npm run front-end-install
      - run:
          name: Install Backend
          command: npm run back-end-install
      # Building Front-Back Ends
      - run:
          name: Build Frontend
          command: npm run front-end-build
      - run:
          name: Build Backend
          command: npm run back-end-build
      # Deploying Front-Back Ends
      - run:
          name: Deploy Frontend
          command: npm run front-end-deploy
      - run:
          name: Deploy Backend
          command: npm run back-end-deploy
workflows:
  udagram:
    jobs:
      - build  
      branches:
       only: main          